proxy:
  title: QIB
  logo-url: https://quadram.ac.uk/wp-content/themes/quadram/images/quadram-logo-white.png
  landing-page: /app/SARS2-NORW
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 80
  authentication: none
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: norw
    password: norw
    groups: scientists
  # Docker configuration
  specs:
  - id: SARS2-NORW
    display-name: SARS2-NORW Phylotype
    description: Tracking the changes of SARS2 phylotypes sequenced by NORW
    # container-cmd: []
    container-image: sars2
    container-volumes: [ "/home/ubuntu/sars2_phylotype_changes/app:/app"]
    access-groups: [scientists]

logging:
  file:
    shinyproxy.log